// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANlMz17TPDgowYrbwHLcCs2EcHk267fEc',
    appId: '1:166037034537:web:d77e6b36e1ede50ef26e38',
    messagingSenderId: '166037034537',
    projectId: 'healtcare-dd7ea',
    authDomain: 'healtcare-dd7ea.firebaseapp.com',
    databaseURL: 'https://healtcare-dd7ea-default-rtdb.firebaseio.com',
    storageBucket: 'healtcare-dd7ea.firebasestorage.app',
    measurementId: 'G-E33FEV573C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-UoQaNUb-X2vArqd0a5pVILC0_O7IGU',
    appId: '1:166037034537:android:6b2ac2b9ec233cf5f26e38',
    messagingSenderId: '166037034537',
    projectId: 'healtcare-dd7ea',
    databaseURL: 'https://healtcare-dd7ea-default-rtdb.firebaseio.com',
    storageBucket: 'healtcare-dd7ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo_e_8ztUrFHMyK-Vxh7QYNy8JFlcni24',
    appId: '1:166037034537:ios:37a9d699ac33925cf26e38',
    messagingSenderId: '166037034537',
    projectId: 'healtcare-dd7ea',
    databaseURL: 'https://healtcare-dd7ea-default-rtdb.firebaseio.com',
    storageBucket: 'healtcare-dd7ea.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
